// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO iam.identities (id, email, password, name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateIdentityParams struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const identity = `-- name: Identity :one
SELECT id, email, password, name, created_at, updated_at FROM iam.identities
WHERE id = $1
`

func (q *Queries) Identity(ctx context.Context, id pgtype.UUID) (IamIdentity, error) {
	row := q.db.QueryRow(ctx, identity, id)
	var i IamIdentity
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityByEmail = `-- name: IdentityByEmail :one
SELECT id, email, password, name, created_at, updated_at FROM iam.identities
WHERE email = $1
`

func (q *Queries) IdentityByEmail(ctx context.Context, email string) (IamIdentity, error) {
	row := q.db.QueryRow(ctx, identityByEmail, email)
	var i IamIdentity
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
