// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IamIdentity struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
